diff a/drivers/input/touchscreen/ft3418_i2c/Makefile b/drivers/input/touchscreen/ft3418_i2c/Makefile	(rejected hunks)
@@ -1,17 +1,18 @@
-# Makefile for the focaltech touchscreen drivers.
-
-
-obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_core.o
-obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_ex_fun.o
-obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_ex_mode.o
-obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_gesture.o
-obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_esdcheck.o
-obj-$(CONFIG_TOUCHSCREEN_FTS)   +=  focaltech_point_report_check.o
-
-
-obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_flash.o
-obj-$(CONFIG_TOUCHSCREEN_FTS)   +=  focaltech_flash/focaltech_upgrade_ft3418.o
-
-
-
-obj-$(CONFIG_TOUCHSCREEN_FTS)   +=  focaltech_i2c.o
+# Makefile for the focaltech touchscreen drivers.
+
+
+obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_core.o
+obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_ex_fun.o
+obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_ex_mode.o
+obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_gesture.o
+obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_esdcheck.o
+obj-$(CONFIG_TOUCHSCREEN_FTS)   +=  focaltech_point_report_check.o
+obj-$(CONFIG_TOUCHSCREEN_FTS)   +=  focaltech_test/
+
+
+obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_flash.o
+obj-$(CONFIG_TOUCHSCREEN_FTS)   +=  focaltech_flash/
+
+
+
+obj-$(CONFIG_TOUCHSCREEN_FTS)   +=  focaltech_i2c.o
